# For more info on HTTP files go to https://aka.ms/vs/httpfile

@baseUrl = https://localhost:7052

### Learning tree (Get all markdown files in the Learning direcotry).
GET {{baseUrl}}/api/learning/tree

### Get ML notes
GET {{baseUrl}}/api/learning/content/Notes/MachineLearning.md

### Get ML journal
GET {{baseUrl}}/api/learning/content/Journal/MachineLearning.md